import Sidebar from '@/components/Sidebar';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {/* <div className="flex bg-slate-50 min-h-screen"> */}
        <div className="bg-slate-100 min-h-screen w-full">
          {/* Sidebar hanya muncul jika bukan di halaman login */}
          {/* <Sidebar />  */}
          {/* <main className="flex-1 ml-64 p-8"> */}
            {children}
          {/* </main> */}
        </div>
      </body>
    </html>
  );
}
